# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e04136a60584526c893e88343e08abe3bcf2004297d90ffb8d36db2350209b4c85361a98e3092110f0a43570cf563c34c992a6ba9b42185ddb18fc4a33818d

test:
  secret_key_base: 0f9209171f252410e0f44b3b02e247faf8fbe2924e89c2a27b768d97ba9a22fea790279189c68abafc079bbd7195d81094f6a505ecaaca57dd526a25910ff724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
